### ISSUE TITLE
Custom validation won't work

### ISSUE THREAD

**Issue by zimt28** [meteortemplates/forms#69] opened 2015-06-01 19:13 UTC
I want to have a password field with confirmation. But it's just not possible for me to access the other field. So whenever I use the `confirmPassword` field, I don't get the value of `password` logged but `undefined`.

```coffee
password:
  type: String
confirmPassword:
  type: String
  custom: ->
    console.log @field('password').value
    if @value isnt @field('password').value
      return 'passwordMismatch'
```
Looks right to me, any idea?

**Comment by jonjamz** [comment] 2015-06-02 00:26
I'm not sure, but there was an earlier issue like this that was apparently resolved:

https://github.com/meteortemplates/forms/issues/4

Let me know if that's of any help.

**Comment by gibson** [comment] 2015-06-11 18:06
Yes this is true, but i dont know this is bug or feature))))
In row 671 https://github.com/meteortemplates/forms/blob/master/lib/module.coffee#L671
validating only one field of all data and when you use ` @field('password')` SimpleSchema dont know about this field

i have same problem and dont know how resolve this((

**Comment by jonjamz** [comment] 2015-12-23 15:10
Closing because #84 is a duplicate of this issue and this has been resolved in the upcoming release.

**Closed by jonjamz** 2015-12-23 15:10 UTC
Labels: help wanted
